### ISSUE TITLE
fd-dired not working?

### ISSUE THREAD

**Issue by benkio** [yqrashawn/fd-dired#16]
Hi,
I'm trying the library because I want a cross-platform alternative to `find`/`grep` and I end up looking at `fd-dired`.
I installed `ripgrep` and `fd`, but when I try a `fd-name-dired` I get an error back.
I recorded a screencast, these are my system info & the `fd-dired` package info from `list-packages`:
`GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6`
```
     Status: Installed in ‘fd-dired-20210311.321/’ (unsigned).
    Version: 20210311.321
     Commit: 7d18938751d047eef18bfb5975195419f0d1e2d3
    Summary: find-dired alternative using fd
   Requires: emacs-25
   Homepage: https://github.com/yqrashawn/fd-dired
   Keywords: tools fd find dired 
 Maintainer: Rashawn Zhang <namy.19@gmail.com>
     Author: Rashawn Zhang <namy.19@gmail.com>
Other versions: 20210311.321 (melpa), 0.1.0 (melpa-stb).
```

What I'm doing wrong?
Thank in advance for your help

https://user-images.githubusercontent.com/4698396/115455984-8b9b6b00-a21a-11eb-9d8d-05cd442a0709.mov

**Comment by grolongo** [comment]
This issue also occurs on Windows 10.
Commands `fd-name-dired`, `fd-dired` and `fd-grep-dired` all return the same error as OP.

**Comment by tom-bowles** [comment]
I get the same on Windows. It appears to be because there's no case for windows in the defcustom for `fd-dired-ls-option`. Since this causes a nil to be used as the default, and this doesn't satisfy the type requirements for the customize widgets used, `M-x customize-variable fd-dired-ls-option` just displays a generic widget to enter the value. I was able to get fd-dired to work by setting this value to `'(" | xargs -0 ls -ld --quoting-style=literal | uniq" . "-ld")`, after which the customize widget started displaying properly (i.e. showing separate fields for the two parts of the cons).

I have the Cygwin utilities on the path, so xargs and ls are available and behave similarly to linux. Given this (or something similar based on WSL) is probably the most common setup for ntemacs, perhaps it's worth making the pcase in the defcustom for `fd-dired-ls-option` return the same for `windows-nt` as it returns for `gnu/linux`?

**Comment by grolongo** [comment]
@tom-bowles I just tested your solution and it works fine on my side too. Note that I'm using Git for Windows with Git BASH (MINGW32) for the GNU tools and don't have any problem neither.

Maybe a bit off-optic but I used the same value without `--quoting-style=literal` to test on macOS since I want to keep the BSD version provided by default and it works fine too. Don't know the side effect that could arise though.

**Comment by grolongo** [comment]
I think this is a better solution for `fd-dired-ls-option`.
It handles all different systems (macOS, Linux and Windows) and either if GNU utils with `gls` is available on macOS or not.

```elisp
(pcase system-type
  ('darwin
   (if (executable-find "gls")
       `(,(concat "| xargs -0 " "gls -ld --quoting-style=literal | uniq") . "-ld")
     `(,(concat "| xargs -0 " insert-directory-program " -ld | uniq") . "-ld")))
  (t
   `(,(concat "| xargs -0 " insert-directory-program" -ld --quoting-style=literal | uniq") . "-ld")))
```

I'm not sure if `--quoting-style=literal` is necessary at all. I couldn't reproduce the whitespace issue raised on #4 on macOS.

So this makes it work anywhere and doesn't throw an error asking to install the whole set of GNU tools in order to use this package.

@yqrashawn @stardiviner I saw you guys working on this, what do you think?

**Comment by stardiviner** [comment]
> I'm not sure if `--quoting-style=literal` is necessary at all. I couldn't reproduce the whitespace issue raised on #4 on macOS.

I can confirm this problem. And it's necessary on macOS.
Also, `gls` is not built-in on macOS. So you should remind user how to install `gls` through `brew install coreutils`.
Currently fd-dired already merged my PR, you can update based on current code.

**Comment by grolongo** [comment]
> I can confirm this problem. And it's necessary on macOS.

Would you mind giving me an example on how to reproduce an error?

I'm literally using `(setq fd-dired-ls-option '("| xargs -0 ls -ld | uniq" . "-ld"))` on macOS with default `ls` and I tested it with whitespaces named folders and files. I didn't have any problem/error.

Thanks!

**Comment by stardiviner** [comment]
Don't know how to provide this example. Seems can not.

**Comment by yqrashawn** [comment]
Thanks to @grolongo's PR. @benkio does it works on your side?

**Comment by benkio** [comment]
> Thanks to @grolongo's PR. @benkio does it works on your side?

Unfortunately I don't have a chance to test it, I moved from Windows now, apologies 🙇 
I will close this issue then, I guess if someone encounter the same issue again he should be able to find it.
Thanks everybody for the support and work ❤️

**Comment by ylluminarious** [comment]
I'm experiencing this issue despite being on the latest build of `fd-dired` and `fd`. I'm using the default stock settings. My issue is almost exactly the same as OP's. It seems to happen randomly, depending on what the search query is and the filename in question.

For example, when I search for a filename which happens to begin with a hyphen and a space (`- `), I get this error:

```
gls: invalid option --        ' '
  Try 'gls --help' for     more information.
```

This same kind of thing happens for all sorts of other files with odd filenames. I can't seem to reproduce this reliably, since some filenames are normal and don't cause any problems. The problem seems to be that the output isn't be sanitized or quoted properly. I don't think this should even be happening in the first place.

Can anyone help me out? I'm just using the stock, default settings (no customizations of my own whatsoever).

**Comment by yqrashawn** [comment]
> I'm experiencing this issue despite being on the latest build of `fd-dired` and `fd`. I'm using the default stock settings. My issue is almost exactly the same as OP's. It seems to happen randomly, depending on what the search query is and the filename in question.
> 
> For example, when I search for a filename which happens to begin with a hyphen and a space (`- `), I get this error:
> 
> ```
> gls: invalid option --        ' '
>   Try 'gls --help' for     more information.
> ```
> 
> This same kind of thing happens for all sorts of other files with odd filenames. I can't seem to reproduce this reliably, since some filenames are normal and don't cause any problems. The problem seems to be that the output isn't be sanitized or quoted properly. I don't think this should even be happening in the first place.
> 
> Can anyone help me out? I'm just using the stock, default settings (no customizations of my own whatsoever).

Hi, may I ask what's you `insert-directory-program` value.

**Comment by ylluminarious** [comment]
@yqrashawn My value for `insert-directory-program` is: `"gls"`
